Term 1:
Starts Wed. 6th September
Ends Fri. 27th October

Term 2:
Mon. 6th November
Wed. 20th December

Term 3:
Mon. 8th January
Fri. 9th Febuary

Term 4:
Mon. 19th Febuary
Fri. 22nd March

Term 5:
Mon. 8th April
Fri. 24th May

Term 6:
Mon. 3rd June
Fri. 28th June




Please note that the campuses are closed on the following days to students for staff training:
Wednesday 25 October
Wednesday 20 March
